# Generated by Django 3.2.9 on 2021-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'food'), ('beverage', 'beverage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('vegetables', 'vegetables'), ('sweet', 'sweet'), ('fruit', 'fruit'), ('cold-drink', 'cold-drink'), ('coffee', 'coffee')], max_length=50, null=True),
        ),
    ]
